### ISSUE TITLE
Connecting to a dedicated mysql container

### ISSUE THREAD

**Issue by meerestier** [ronanguilloux/akeneo-pim-docker#1]
Hi there,

I got your container to work on Kitematic… Now if I understand correctly, if the container is destroyed, all data goes with it…

How would I connect to a different mysql host (ideally a docker container itself)

Thx

Lars

**Comment by ronanguilloux** [comment]
Hi @meerestier,
short answer is: use docker-compose instead, to build a multi-container solution.
This one is a single container, on purpose, because Kitematic doesn't know how to deal with docker-compose based container architectures :-|.
